### ISSUE TITLE
仓库无了

### ISSUE THREAD

**Issue by YidaozhanYa** [antman666/kernel-repo#3]
![image](https://user-images.githubusercontent.com/73830635/160242043-5c6b0b6b-bc7d-4a20-bee1-7b496e998342.png)
![image](https://user-images.githubusercontent.com/73830635/160242047-f0faa542-00aa-4464-a9c6-e21265eb3def.png)

**Comment by antman666** [comment]
我删的，积累太多会限制上传releases😢
